name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test shop -v 2
    - uses: revanth-reddy/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: a5290134-68ac-4667-aec4-07f7245df90f
          heroku_app_name: "raitubazaar" #Must be unique in Heroku
          heroku_email: "malerevanthreddy3099@gmail.com"
